def get_folder_name(extension):
    if not extension:
        return None

    # List of key value pair extensions to be sorted into folders based on their value
    folders = {
        'pdf': 'PDFs',
        'mp3': 'Music',
        'mp4': 'Videos',
        'doc': 'Documents',
        'rtf': 'Documents',
        'odt': 'Documents',
        'docx': 'Documents',
        'docm': 'Documents',
        'dotx': 'Documents',
        'dot': 'Documents',
        'xml': 'Documents',
        'djvu': 'Documents',
        'xltx': 'Excel',
        'xlsm': 'Excel',
        'xltm': 'Excel',
        'xlam': 'Excel',
        'xlsx': 'Excel files',
        'xls': 'Excel files',
        'txt': 'Text files',
        'ppt': 'PPT files',
        'class': 'Java programs',
        'py': 'Python files',
        'php': 'PHP programs',
        'perl': 'Perl programs',
        'exe': 'Software',
        'java': 'Java programs',
        'c': 'C programs',
        'go': 'Go programs',
        'rb': 'Ruby programs',
        'rs': 'Rust programs',
        'cpp': 'CPP programs',
        'scala': 'Scala programs',
        'swift': 'Swift programs',
        'vb': 'Visual Basic programs',
        'svg': 'Vector graphics',
        'eps': 'Vector graphics',
        'ai': 'Vector graphics',
        'dwg': 'CAD files',
        'dxf': 'CAD files',
        'skp': '3D models',
        '3ds': '3D models',
        'obj': '3D models',
        'fbx': '3D models',
        'dae': '3D models',
        'stl': '3D models',
        'prt': '3D models',
        'sldprt': '3D models',
        'step': '3D models',
        'iges': '3D models',
        'brep': '3D models',
        'dgn': 'CAD files',
        'ifc': 'CAD files',
        'rvt': 'CAD files',
        'dwfx': 'CAD files',
        'dwf': 'CAD files',
        'dwfx': 'CAD files',
        '3mf': '3D models',
        'ply': '3D models',
        'raw': 'Images',
        'png': 'Images',
        'jpg': 'Images',
        'jpeg': 'Images',
        'mkv': 'Videos',
        'zip': 'Archives',
        'rar': 'Archives',
        '7z': 'Archives',
        'tar': 'Archives',
        'gzip': 'Archives',
        'bzip2': 'Archives',
        'xz': 'Archives',
        'html': 'Web files',
        'css': 'Web files',
        'js': 'Web files',
        'php': 'Web files',
        'swf': 'Web files',
        'ods': 'Spreadsheets',
        'odp': 'Presentations',
        'bmp': 'Images',
        'gif': 'Images',
        'ico': 'Images',
        'wmv': 'Videos',
        'flv': 'Videos',
        'avi': 'Videos',
        'mov': 'Videos',
        'aac': 'Audio',
        'flac': 'Audio',
        'wma': 'Audio',
        'aif': 'Audio',
        'aiff': 'Audio',
        'mid': 'Audio',
        'midi': 'Audio',
        'm4a': 'Audio',
        'aa': 'Audio',
        'aax': 'Audio',
        'wav': 'Audio',
        'm4v': 'Videos',
        'm4p': 'Audio',
        'wma': 'Audio',
        'wv': 'Audio',
        'ogg': 'Audio',
        'ogv': 'Videos',
        'oga': 'Audio',
        'ogx': 'Audio',
        'opus': 'Audio',
        'webm': 'Video',
        'flac': 'Audio',
        'opus': 'Audio',
        'mka': 'Audio',
        'bmp': 'Images',
        'gif': 'Images',
        'ico': 'Images',
        'wmv': 'Videos',
        'flv': 'Videos',
        'avi': 'Videos',
        'mov': 'Videos',
        'aac': 'Audio',
        'flac': 'Audio',
        'wma': 'Audio',
        'aif': 'Audio',
        'aiff': 'Audio',
        'mid': 'Audio',
        'midi': 'Audio',
        'm4a': 'Audio',
        'aa': 'Audio',
        'aax': 'Audio',
        'wav': 'Audio',
        'm4v': 'Videos',
        'm4p': 'Audio',
        'wma': 'Audio',
        'wv': 'Audio',
        'ogg': 'Audio',
        'ogv': 'Videos',
        'oga': 'Audio',
        'ogx': 'Audio',
        'opus': 'Audio',
        'webm': 'Video',
        'flac': 'Audio',
        'ra': 'Audio',
        'rm': 'Audio',
        'ram': 'Audio',
        'au': 'Audio',
        'snd': 'Audio',
        'spx': 'Audio',
        'tlc': 'Audio',
        'vox': 'Audio',
        'vsd': 'Drawing',
        'vdx': 'Drawing',
        'vsdx': 'Drawing',
        'vst': 'Drawing',
        'vtx': 'Drawing',
        'vss': 'Drawing',
        'vsx': 'Drawing',
        'vstm': 'Drawing',
        'vssm': 'Drawing',
        'odg': 'Drawing',
        'pub': 'Publisher',
        'xps': 'XPS',
        'oxps': 'XPS',
        'mpd': 'Project',
        'mpp': 'Project',
        'mpt': 'Project',
        'mpw': 'Project',
        'mpx': 'Project',
        'mspdi': 'Project',
        'mpptx': 'Project',
        'mptx': 'Project',
        'epub': 'eBook',
        'gpx': 'GPX file',
        
    }
    # Gets an extension's value, if it doesn't exist then this will sort the remaining into "Other" folder
    return folders.get(extension, 'Other')
